PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET           = ex_uirq
SRC_CC           = ex_uirq.cc
REQUIRES_LIBS    = libstdc++ libpthread
SRC_CC_IS_CXX11  = y

include $(L4DIR)/mk/prog.mk
